# Dockerfile.prod for client/frontend 
# hmm
FROM node:20.11.1 AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

ENV VITE_BASE_URL=/api/v1
RUN npm run build

FROM nginx:1.27.1

RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY ./nginx.prod.conf /etc/nginx/nginx.conf

# COPY ./nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
# COPY ./nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key
COPY ./dhparam.pem /etc/ssl/certs/dhparam.pem

# RUN chmod 640 /etc/ssl/private/nginx-selfsigned.key && \
#     chown root:www-data /etc/ssl/private/nginx-selfsigned.key

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
