# Dockerfile.prod for client/frontend
FROM node:20.11.1 AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN yarn install

COPY . .

ENV VITE_BASE_URL=/api/v1
RUN npm run build

FROM nginx:1.27.1

RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY ./nginx.prod.conf /etc/nginx/nginx.conf


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]