# docker-compose.dev.yml
services:
  server:
    container_name: crm-app-server
    environment:
      NODE_ENV: development
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      # - migrate
      - database-sql
    command: ["npx", "tsx", "watch", "src/index.ts"]
    env_file:
      - server/.env.development

  spring-server:
    container_name: crm-app-spring-server
    build:
      context: ./spring-server/crm-app
      dockerfile: Dockerfile.dev
    depends_on:
      - database-sql
    env_file:
      - spring-server/crm-app/.env.development
    volumes:
      - ./spring-server/crm-app:/app

  # spring-test:
  #   container_name: crm-app-spring-test
  #   build:
  #     context: ./spring-server/crm-app
  #     dockerfile: Dockerfile.dev
  #   depends_on:
  #     - database-sql
  #   env_file:
  #     - spring-server/crm-app/.env.development
  #   command: ./mvnw test
  #   volumes:
  #     - ./spring-server/crm-app:/app
  #   environment:
  #     SPRING_PROFILES_ACTIVE: test

  database-sql:
    container_name: crm-app-postgresql-db
    image: postgres:16.4-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - server/.env.development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patrick -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432" #for local JB DataGrip connection

  # cron-job:
  #   container_name: crm-app-cron-job
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile.dev
  #   env_file:
  #     - server/.env.development
  #   depends_on:
  #     - database-sql
  #     - server
  #   volumes:
  #     - ./server:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command:
  #     [
  #       "/bin/sh",
  #       "-c",
  #       "while true; do npx tsx src/db/generate-fake-orders.ts; sleep 60; done",
  #     ]

  migrate:
    container_name: crm-app-db-migrate
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: /bin/sh -c "npm run db:migrate:script:test && npm run db:migrate:script"
    depends_on:
      - database-sql
    environment:
      - NODE_ENV=development
    env_file:
      - server/.env.development

  client:
    container_name: crm-app-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    env_file:
      - client/.env.development

  nginx:
    image: nginx:1.27.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy
    restart: always
    depends_on:
      - server
      - client
      - spring-server

  report-generator:
    container_name: crm-app-report-generator
    build:
      context: ../crm-app-report-generator-service
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ../crm-app-report-generator-service/src:/app
      - /app/tmp
      - ../crm-app/development.env.dev:/app/.env
    env_file:
      - server/.env.development  
    depends_on:
      - database-sql
    

volumes:
  postgres_data:
