@baseUrl = http://localhost/api/v1
@baseUrlStag = http://ec2-13-60-156-45.eu-north-1.compute.amazonaws.com/api/v1


## DEV

### POST register user
POST {{baseUrl}}/auth/register HTTP/1.1
content-type: application/json

{
  "username": "cytt3heippa",
  "email": "uut@testi.fi",
  "password": "salasana",
  "firstName": "Patrick",
  "lastName": "Sel",
  "role": "user",
  "phone": "0401234567",
  "address": "Testikatu 2",
  "city": "Turku",
  "postalCode": "20100",
  "country": "Suomi"
}

### POST /auth/login
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
  "email": "patu@testi.fi",
  "password": "salasana"
}

### GET /auth/me
GET {{baseUrl}}/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwNjczODhlLThjMTMtNDE2ZC1hMjhjLTRkOGFkZjFmM2U5MSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM3MzU0Nzc3LCJleHAiOjE3MzczNTQ3OTJ9.Q20fJTEH3xdXjJ2UyjSRoNlrlP1CYXZOCg1aC3eN0-A
### POST /auth/refresh
POST {{baseUrl}}/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwNjczODhlLThjMTMtNDE2ZC1hMjhjLTRkOGFkZjFmM2U5MSIsImlhdCI6MTczNzM1MzA3MSwiZXhwIjoxNzM5NzcyMjcxfQ.19RDXB0HCJReFGA099qgeMmsqBHVIpyZ8PfsWquatfs"
}




# AWS AWS AWS AWS

### POST registeer user
POST {{baseUrlStag}}/auth/register HTTP/1.1
content-type: application/json

{
  "username": "stag",
  "email": "stagt@stag.fi",
  "password": "salasana",
  "firstName": "Patrick",
  "lastName": "Sel",
  "role": "user",
  "phone": "0401234567",
  "address": "Testikatu 2",
  "city": "Turku",
  "postalCode": "20100",
  "country": "Suomi"
}

### POST login user // this is aws test user
POST {{baseUrlStag}}/auth/login HTTP/1.1
content-type: application/json

{
  "email": "stagt@stag.fi",
  "password": "salasana"
}

### GET /auth/me
GET {{baseUrlStag}}/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmYjZmYmM3LTI1NmYtNGIwYy1iMmM5LTc1ZDAzYzliOThkNSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM3MTg5ODc0LCJleHAiOjE3MzcxOTA3NzR9.HWNfaFHnwNKF4TmBupRQZvFORsNOiFLQn2551xvbW6s

