@baseUrl = http://localhost/api/v1
@baseUrlStag = http://ec2-13-60-156-45.eu-north-1.compute.amazonaws.com/api/v1


## DEV

### POST register user
POST {{baseUrl}}/auth/register HTTP/1.1
content-type: application/json

{
  "username": "c1y7egtt3heippa",
  "email": "1c7teyutgt@testi.fi",
  "password": "salasana",
  "firstName": "Patrick",
  "lastName": "Sel",
  "role": "user",
  "phone": "0401234567",
  "address": "Testikatu 2",
  "city": "Turku",
  "postalCode": "20100",
  "country": "Suomi"
}

### POST /auth/login
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
  "email": "patu@testi.fi",
  "password": "salasana"
}

### GET /auth/me
GET {{baseUrl}}/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwNjczODhlLThjMTMtNDE2ZC1hMjhjLTRkOGFkZjFmM2U5MSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM3MTkxNDMzLCJleHAiOjE3MzcxOTIzMzN9.MpUtHzrTS6bY4QbY2c0mrkacMe4k54nZLJQA7JLculg



### POST /auth/refresh
POST {{baseUrl}}/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwNjczODhlLThjMTMtNDE2ZC1hMjhjLTRkOGFkZjFmM2U5MSIsImlhdCI6MTczNzE5MDE0OSwiZXhwIjoxNzM5NjA5MzQ5fQ.g2XrSL-TkG3kHzpIG6OKTW0R288DnuF9Q2XSyW2-TAo"
}




# AWS

### POST registeer user
POST {{baseUrlStag}}/auth/register HTTP/1.1
content-type: application/json

{
  "username": "stag",
  "email": "stagt@stag.fi",
  "password": "salasana",
  "firstName": "Patrick",
  "lastName": "Sel",
  "role": "user",
  "phone": "0401234567",
  "address": "Testikatu 2",
  "city": "Turku",
  "postalCode": "20100",
  "country": "Suomi"
}

### POST login user // this is aws test user
POST {{baseUrlStag}}/auth/login HTTP/1.1
content-type: application/json

{
  "email": "stagt@stag.fi",
  "password": "salasana"
}

### GET /auth/me
GET {{baseUrlStag}}/auth/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmYjZmYmM3LTI1NmYtNGIwYy1iMmM5LTc1ZDAzYzliOThkNSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM3MTg5ODc0LCJleHAiOjE3MzcxOTA3NzR9.HWNfaFHnwNKF4TmBupRQZvFORsNOiFLQn2551xvbW6s

