@baseUrl = http://localhost/api/v1

### GET all test items
# GET http://localhost/api/v1/test HTTP/1.1
GET {{baseUrl}}/test HTTP/1.1

###
### POST testItem
POST {{baseUrl}}/test HTTP/1.1
content-type: application/json

{
    "content": "Sample Test Content 22stag",
    "important": true
}

### GET health
GET http://localhost:80/api/v1/health HTTP/1.1

### GET /customers
GET {{baseUrl}}/customers HTTP/1.1

### GET /customers, with query params
GET {{baseUrl}}/customers?page=1&limit=3 HTTP/1.1
# /customers?search=John&sort=city:asc&page=1&limit=10

### GET /customers/summary
GET {{baseUrl}}/customers/summary HTTP/1.1

### GET /customers/summary, with query params
GET {{baseUrl}}/customers/summary?page=1&limit=3&sort=totalSpent:desc HTTP/1.1

### GET /customers/:id
GET {{baseUrl}}/customers/9182a36b-77e3-484f-b7c2-1c0c0194e4a5 HTTP/1.1

### GET /customers/:id/orders , overview of all orders from a customer (customer dashboard)
GET {{baseUrl}}/customers/9182a36b-77e3-484f-b7c2-1c0c0194e4a5/orders HTTP/1.1

### GET /customers/:id/orders/:orderId"
GET {{baseUrl}}/customers/9182a36b-77e3-484f-b7c2-1c0c0194e4a5/orders/e551617b-6756-4a78-b574-b6d8913fae05 HTTP/1.1

### GET
## ??

### POST /customers
POST {{baseUrl}}/customers HTTP/1.1
content-type: application/json

{
  "firstName": "Jukka33",
  "lastName": "Poika2",
  "email": "jukka33@example.fi",
  "phone": "2401234567",
  "address": "Heippakatu 12",
  "city": "Helsinki",
  "postalCode": "00100",
  "country": "Suomi"
}

### UPDATE /customers/:id
PUT {{baseUrl}}/customers/d7a99d84-b15f-4680-bae5-86b1d27e8f89 HTTP/1.1
content-type: application/json

{
  "firstName": "Jukka4",
  "lastName": "Poika",
   "city": "Helsinkicity"
}

### DELETE /customers/:id
DELETE {{baseUrl}}/customers/4db65805-a85f-4930-898f-c85cbc8aa91b HTTP/1.1
content-type: application/json


### 
### aws staging
### POST testItem
POST http://ec2-13-60-156-45.eu-north-1.compute.amazonaws.com/api/v1/test HTTP/1.1
content-type: application/json

{
    "content": "Sample Test Content live57stag",
    "important": true,
    "wiolw": 3
}


