@baseUrl = http://localhost/api/v1
@baseUrlStag = http://ec2-13-60-156-45.eu-north-1.compute.amazonaws.com/api/v1

@access-token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc3MzMxNWY1LWZjM2UtNGFkMS05OTY4LTQxMWMxMjJjZDgxOCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM3OTgxNDM2LCJleHAiOjE3Mzc5ODIzMzZ9.98_u3hCnOZuH02a1gYCCreVivckd634apDvsVHtE5-4
@access-token-stag = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmYjZmYmM3LTI1NmYtNGIwYy1iMmM5LTc1ZDAzYzliOThkNSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM3Mjk2Mzg1LCJleHAiOjE3MzcyOTcyODV9.6Qcgi2l7AY-Un80gKhomLpEj9IJZOf5M3ilgrGPL-KQ


### GET health
GET http://localhost:80/api/v1/health HTTP/1.1

### GET /customers
GET {{baseUrl}}/customers HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers, with query params
GET {{baseUrl}}/customers?search=John&sort=firstName:asc&page=1&limit=3 HTTP/1.1
# /customers?search=John&sort=firstName:asc&page=1&limit=3
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/summary
GET {{baseUrl}}/customers/summary HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/summary, with query params
GET {{baseUrl}}/customers/summary?&page=1&limit=10sort=numOfOrders:desc HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/:id
GET {{baseUrl}}/customers/a3cd1535-5cfb-4e9d-a200-87919f6890f5 HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/:id/orders , overview of all orders from a customer (customer dashboard)
GET {{baseUrl}}/customers/a3cd1535-5cfb-4e9d-a200-87919f6890f5/orders HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/:id/orders/:orderId"
GET {{baseUrl}}/customers/a3cd1535-5cfb-4e9d-a200-87919f6890f5/orders/6b36de67-4867-457f-ad85-4084204b75cf HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### POST /customers
POST {{baseUrl}}/customers HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

{
  "firstName": "cJwuskka33",
  "lastName": "Poikas2",
  "email": "jucckwksadd33@example.fi",
  "phone": "2401234567",
  "address": "Heippakatu 12",
  "city": "Helsinki",
  "postalCode": "00100",
  "country": "Suomi"
}

### UPDATE /customers/:id
PUT {{baseUrl}}/customers/995dd88b-35ba-4863-88fc-1e4ae7f517e7 HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

{
  "firstName": "Jukka4",
  "lastName": "Poika",
   "city": "Helsinkicity"
}

### DELETE /customers/:id
DELETE {{baseUrl}}/customers/771a2fac-210d-4d40-8412-6ea69aa41dc9 HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json


### 
### AWS STAGING


### GET health
GET http://localhost:80/api/v1/health HTTP/1.1

### GET /customers
GET {{baseUrlStag}}/customers HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers, with query params
GET {{baseUrlStag}}/customers?sort=firstName:asc HTTP/1.1
# /customers?search=John&sort=firstName:asc&page=1&limit=3
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/summary
GET {{baseUrlStag}}/customers/summary HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/summary, with query params
GET {{baseUrlStag}}/customers/summary?&page=1&limit=10sort=numOfOrders:desc HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/:id
GET {{baseUrlStag}}/customers/a3cd1535-5cfb-4e9d-a200-87919f6890f5 HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/:id/orders , overview of all orders from a customer (customer dashboard)
GET {{baseUrlStag}}/customers/a3cd1535-5cfb-4e9d-a200-87919f6890f5/orders HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### GET /customers/:id/orders/:orderId"
GET {{baseUrlStag}}/customers/a3cd1535-5cfb-4e9d-a200-87919f6890f5/orders/6b36de67-4867-457f-ad85-4084204b75cf HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

### POST /customers
POST {{baseUrlStag}}/customers HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

{
  "firstName": "cJwuskka33",
  "lastName": "Poikas2",
  "email": "jucckwksadd33@example.fi",
  "phone": "2401234567",
  "address": "Heippakatu 12",
  "city": "Helsinki",
  "postalCode": "00100",
  "country": "Suomi"
}

### UPDATE /customers/:id
PUT {{baseUrlStag}}/customers/995dd88b-35ba-4863-88fc-1e4ae7f517e7 HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json

{
  "firstName": "Jukka4",
  "lastName": "Poika",
   "city": "Helsinkicity"
}

### DELETE /customers/:id
DELETE {{baseUrlStag}}/customers/995dd88b-35ba-4863-88fc-1e4ae7f517e7 HTTP/1.1
Authorization: Bearer {{access-token}}
Content-Type: application/json