

### GET spring
GET http://localhost:80/api/v1/products/test HTTP/1.1


### GET node
GET http://localhost:80/api/v1/customers/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwNjczODhlLThjMTMtNDE2ZC1hMjhjLTRkOGFkZjFmM2U5MSIsImZpcnN0TmFtZSI6IlBhdHJpY2siLCJyb2xlIjoidXNlciIsImlhdCI6MTczNzYyMzY5NSwiZXhwIjoxNzM3NjI0NTk1fQ.wpV0DZtL8S0IPxhBy_HbzW7p4JeFgOqbjsEkvlfCKns


### GET spring - local non docker
GET http://localhost:8080/api/v1/products/test HTTP/1.1

### GET spring
GET http://localhost:35729/api/v1/products/test HTTP/1.1