# Dockerfile.prod for server/backend

FROM node:20.11.1 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

# create prod image
FROM node:20.11.1

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/build ./build
COPY ./migrations /usr/src/app/migrations
COPY global-bundle.pem  /usr/src/app/global-bundle.pem

COPY vitest.integration.config.ts /usr/src/app/vitest.integration.config.ts
COPY vitest.unit.config.ts /usr/src/app/vitest.unit.config.ts

RUN groupadd -r nodejs && useradd -r -g nodejs nodejs
RUN chown -R nodejs:nodejs /usr/src/app
USER nodejs

# CMD node build/src/index.js
CMD ["node", "build/src/index.js"]
