# Dockerfile.dev for Node.js server/backend
FROM node:20.11.1-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN yarn install
RUN yarn add global tsx

COPY . .

FROM node:20.11.1-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

RUN addgroup -S nodejs && adduser -S nodejs -G nodejs
RUN chown -R nodejs:nodejs /usr/src/app
USER nodejs

CMD ["sh", "-c", "npm run dev & tsx /src/db/run-sql-job.ts"]