# Dockerfile.prod for Spring Boot server/backend
# Stage 1: Build
FROM eclipse-temurin:21-jdk AS build
WORKDIR /app

COPY ./mvnw .
COPY ./mvnw.cmd .
COPY ./pom.xml .
COPY ./.mvn ./.mvn

RUN ./mvnw dependency:resolve dependency:resolve-plugins

COPY ./src ./src

RUN ./mvnw package -DskipTests

# Stage 2: Prod image
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
