# Dockerfile.dev for Spring Boot
FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY ./mvnw .
COPY ./mvnw.cmd .
COPY ./pom.xml .
COPY ./.mvn ./.mvn

RUN ./mvnw dependency:resolve dependency:resolve-plugins

COPY ./src ./src

# Expose app and LiveReload
# EXPOSE 8080 35729

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=developer"]