spring.application.name=crm-app

# Common DB stuff
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DEV DB
spring.datasource.url=jdbc:postgresql://database-sql:5432/crm_app_db_dev
spring.datasource.username=patrick
spring.datasource.password=jlafei8910fQQ-Hw92.W1l
spring.profiles.active=dev


#spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
logging.level.org.springframework.boot.devtools=DEBUG
spring.devtools.livereload.port=35729
