spring.application.name=crm-app
spring.profiles.active=dev

# PostgreSQL
spring.datasource.url=jdbc:postgresql://database-sql:5432/crm_app_db_dev
spring.datasource.username=patrick
spring.datasource.password=jlafei8910fQQ-Hw92.W1l
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none


spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
logging.level.org.springframework.boot.devtools=DEBUG
spring.devtools.livereload.port=35729

spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false