# Test database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/crm_app_db_test
spring.datasource.username=patrick
spring.datasource.password=jlafei8910fQQ-Hw92.W1l
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate and JPA configuration for tests
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Additional properties for tests
spring.test.database.replace=none
