name: Clear Cache

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear GitHub Cache
        run: |
          echo "Clearing caches..."
          curl -X DELETE \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/caches"
          echo "Cache cleared!"