name: Unit and Integration Tests

on:
  push:
    paths-ignore:
      - README.md
      - docs/**

  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  client-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-client-node-${{ hashFiles('client/package-lock.json') }}-${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-client-node-

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./client

      - name: Check style/lint
        run: npm run lint
        working-directory: ./client

      - name: Run TypeScript type checks
        run: npm run typecheck
        working-directory: ./client

      - name: Run npm audit
        run: npm audit --audit-level=high
        working-directory: ./client

      - name: Run frontend unit tests
        run: npm run test:unit:ci
        working-directory: ./client

      - name: Upload frontend coverage results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: client-coverage
          path: client/coverage

  server-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./server/node_modules
          key: ${{ runner.os }}-server-node-${{ hashFiles('server/package-lock.json') }}-${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-server-node-
        continue-on-error: true

      - name: Remove node_modules
        run: rm -rf node_modules package-lock.json
        working-directory: ./server

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Run TypeScript type checks
        run: npm run tsc --noEmit
        working-directory: ./server

      - name: Run npm audit
        run: npm audit --audit-level=high
        working-directory: ./server

      - name: Run server unit tests
        run: npm run test:unit:ci
        working-directory: ./server

      - name: Upload server coverage results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage
          path: server/coverage

  integration-tests:
    needs: [client-unit-tests, server-unit-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      NODE_ENV: test
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: crm_app_db_dev
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      VITE_BASE_URL: /api1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Application with Docker Compose
        run: |
          docker-compose -f docker-compose.ci.yml up -d
          echo "Waiting for services to be ready..."
          until curl -s http://localhost/api1/health; do
            echo "Waiting for backend to be ready..."
            sleep 8
          done
          echo "Services are ready!"

      - name: Create test database if it doesn't exist
        run: |
          echo "Checking if test database exists..."
          if [ "$(docker exec crm-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname = 'crm_app_db_test'")" != "1" ]; then
            echo "Test database does not exist. Creating it now..."
            docker exec crm-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d postgres -c "CREATE DATABASE crm_app_db_test;"
          else
            echo "Test database already exists."
          fi
        shell: bash
        continue-on-error: true

      # - name: Create test database if it doesn't exist
      #   run: |
      #     echo "Creating test database if it doesn't exist..."
      #     docker exec crm-app-postgresql-db \
      #       sh -c "psql -U ${{ secrets.POSTGRES_USER }} -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'crm_app_db_test'\" \
      #       | grep -q 1 || psql -U ${{ secrets.POSTGRES_USER }} -d postgres -c \"CREATE DATABASE crm_app_db_test\""
      #   continue-on-error: true

      - name: Run generate migration files TEST-DB
        run: |
          docker-compose -f docker-compose.ci.yml exec server npm run db:generate:test
        continue-on-error: true

      - name: Run drizzle kit migrations TEST-SB
        run: |
          docker-compose -f docker-compose.ci.yml exec server sh -c "NODE_ENV=test npx drizzle-kit generate"

        continue-on-error: true

      - name: Run migration script TEST-DB
        run: |
          docker-compose -f docker-compose.ci.yml exec server npm run db:migrate:script:test
        continue-on-error: true

      - name: Seed test data in the database
        run: |
          echo "Seeding data into test database..."
          docker exec crm-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d crm_app_db_test -c "
          -- Insert Mock Data for Test items
          INSERT INTO test_items (id, content, important) VALUES
          ('1', 'Test Word 1', true),
          ('2', 'Test Word 2', false),
          ('3', 'Test Word 3', true);

          -- Insert Mock Data for Customers
          INSERT INTO customers (customer_id, first_name, last_name, email, phone, address, city, postal_code, country)
          VALUES
          (gen_random_uuid(), 'John', 'Doe', 'john.doe@example.com', '555-1234', '123 Main St', 'New York', '10001', 'USA'),
          (gen_random_uuid(), 'Jane', 'Smith', 'jane.smith@example.com', '555-5678', '456 Oak Ave', 'San Francisco', '94105', 'USA');
          "
        continue-on-error: true

      # Debug
      - name: Check migration logs
        run: |
          echo "Checking migration logs..."
          docker logs crm-app-db-migrate
        continue-on-error: true

      # Debug
      - name: Check all databases for the user
        run: |
          echo "Listing all databases for user..."
          docker exec crm-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d postgres -c "\l"
        continue-on-error: true

      # Debug
      - name: Check database tables
        run: |
          echo "Listing tables in the TEST database..."
          docker exec crm-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d crm_app_db_test -c "\dt"
        continue-on-error: true

      # Debug
      - name: Check test data exists in table
        run: |
          echo "Listing all rows in the test_items table..."
          docker exec crm-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d crm_app_db_test -c "SELECT * FROM test_items;"

          echo "Listing all rows in the customers table..."
          docker exec crm-app-postgresql-db psql -U ${{ secrets.POSTGRES_USER }} -d crm_app_db_test -c "SELECT * FROM customers;"
        continue-on-error: true

      - name: Run Integration Tests
        run: |
          docker-compose -f docker-compose.ci.yml exec server npm run test:integration:ci

      - name: Upload Integration Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: ./integration-tests/results

      ## test db issue
  e2e-tests:
    needs: [integration-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright dependencies
        run: npm install
        working-directory: ./playwright-e2e

      - name: Install Playwright Browsers
        # run: npx playwright install --with-deps
        run: yarn playwright install --with-deps
        working-directory: ./playwright-e2e
        continue-on-error: true

      # Debug
      - name: Debug
        run: |
          echo "Waiting for services to be ready..."
          until curl -s http://localhost/api1/health; do
            echo "Waiting for backend to be ready..."
            sleep 8
          done
          echo "Services are ready!"
        continue-on-error: true

      # Debug
      - name: Debug
        run: |
          echo "Waiting for services to be ready..."
          until curl -s http://localhost/api1/customers; do
            echo "Waiting for backend to be ready..."
            sleep 8
          done
          echo "Services are ready!"
        continue-on-error: true

      - name: Run E2E tests ########### muista korjata db ongelma
        run: npm run test:e2e
        continue-on-error: true

      # - name: Upload E2E Test Results
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: ./playwright-e2e/playwright-report/
      #     retention-days: 30

      # - name: Upload Screenshots as Artifacts
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: e2e-screenshots
      #     path: ./screenshots/*.png

      # - name: Stop and Remove Containers
      #   run: |
      #     docker-compose -f docker-compose.ci.yml down
