name: Deploy to Staging

on:
  workflow_run:
    workflows: ["Build and Push Production Docker Images"]
    types:
      - completed

jobs:
  deploy-staging:
    name: Deploy Staging Environment
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # infra ylös
      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.9.7

      # - name: Initialize Terraform
      #   run: terraform init
      #   working-directory: ./terraform

      # - name: Validate Terraform
      #   run: terraform validate
      #   working-directory: ./terraform

      # - name: Plan Terraform Changes
      #   run: terraform plan
      #   working-directory: ./terraform

      # - name: Apply Terraform
      #   run: echo "Apply..!"

      #
      # paivita serveri

      - name: Extract Image SHAs
        id: extract-sha
        run: |
          echo "SERVER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/crm-app:server-${{ github.event.workflow_run.outputs.server_image_sha }}" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/crm-app:client-${{ github.event.workflow_run.outputs.client_image_sha }}" >> $GITHUB_ENV

      - name: Debug Image Variables
        run: |
          echo "SERVER_IMAGE=$SERVER_IMAGE"
          echo "FRONTEND_IMAGE=$FRONTEND_IMAGE"

      - name: Debug Image Tags
        run: |
          echo "Server Image: ${{ secrets.DOCKERHUB_USERNAME }}/crm-app:server-${{ github.sha }}"
          echo "Client Image: ${{ secrets.DOCKERHUB_USERNAME }}/crm-app:client-${{ github.sha }}"

      - name: Create .env File for Staging
        run: |
          echo "SERVER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/crm-app:server-${{ github.sha }}" > .env
          echo "FRONTEND_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/crm-app:client-${{ github.sha }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
          echo "DATABASE_URL_STAG=${{ secrets.DATABASE_URL_STAG }}" >> .env

      - name: Configure SSH ffor EC2 Access
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}

      - name: Transfer .env File to EC2
        run: |
          scp -o StrictHostKeyChecking=no .env ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }}:/home/ubuntu/crm-app/.env

      - name: Add EC2 to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.AWS_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Updated Compose to Staging
        run: |
          ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} "
            cd /home/ubuntu/crm-app &&

            echo 'Cleaning working directory...' &&
            git fetch origin dev &&
            git reset --hard origin/dev &&
            git clean -fd &&

            echo 'Stopping existing Docker services...' &&
            docker-compose --env-file .env -f docker-compose.stag.yml down &&

            echo 'Pulling latest Docker images...' &&
            docker-compose --env-file .env -f docker-compose.stag.yml pull &&
            echo 'Starting updated Docker services...' &&
            docker-compose --env-file .env -f docker-compose.stag.yml up --build -d"

      - name: Verify Deployment
        run: |
          ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} "docker ps"

      - name: Debug GitHub SHA
        run: |
          echo "GitHub SHA: ${{ github.sha }}"

      - name: Common Setup on Staging Server
        run: |
          ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
            echo "Switching to project directory..."
            cd /home/ubuntu/crm-app
            pwd

            echo "Loading nvm environment..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            echo "Verifying Node.js and npm versions..."
            node --version
            npm --version
          EOF

      # - name: Run Unit Tests on Staging Server
      #   run: |
      #     ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
      #       echo "Running Unit Tests..."
      #       export NVM_DIR="$HOME/.nvm"
      #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

      #       cd /home/ubuntu/crm-app/
      #       echo "Running unit tests in server-side..."
      #       npm run test:unit:client:ci || exit 1

      #       echo "Running unit tests in client-side..."
      #       npm run test:unit:client:ci" || exit 1

      #       echo "Unit tests passed successfully!"
      #     EOF

      # - name: Run Integration Tests on Staging Server
      #   run: |
      #     ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
      #       echo "Running Integration Tests..."
      #       export NVM_DIR="$HOME/.nvm"
      #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

      #       cd /home/ubuntu/crm-app/
      #       echo "Running Integration tests in server-side..."
      #       npm run test:integration:ci || exit 1

      #       echo "Integration tests passed successfully!"
      #     EOF

      - name: Clean Up Docker Resources on EC2
        run: |
          ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
            echo "Cleaning up Docker resources..."
            docker system prune -af
            echo "Docker cleanup completed!"
            df -h
          EOF

      # # E2# tests

      # - name: Run E2E Tests on Staging Server
      #   run: |
      #     ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
      #       echo "Switching to project directory..."
      #       cd /home/ubuntu/crm-app
      #       pwd

      #       echo "Loading nvm environment..."
      #       export NVM_DIR="$HOME/.nvm"
      #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

      #       echo "Verifying Node.js and npm versions..."
      #       node --version
      #       npm --version

      #       echo "Running E2E tests..."
      #       /home/ubuntu/.nvm/versions/node/v22.12.0/bin/npm run test:e2e
      #        ## or  npm run test:e2e || exit 1 ???
      #       EXIT_CODE=$?

      #       if [ $EXIT_CODE -ne 0 ]; then
      #         echo "E2E tests failed! Exit code: $EXIT_CODE"
      #         exit $EXIT_CODE
      #       else
      #         echo "E2E tests passed successfully!"
      #       fi
      #     EOF

# e2e-tests:
#   needs: [integration-tests]
#   runs-on: ubuntu-latest
#   timeout-minutes: 5

#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: "20"

# - name: Install Playwright dependencies
#   run: npm install
#   working-directory: ./playwright-e2e

# - name: Install Playwright Browsers
#   # run: npx playwright install --with-deps
#   run: yarn playwright install --with-deps
#   working-directory: ./playwright-e2e
#   continue-on-error: true

# # Debug
# - name: Debug
#   run: |
#     echo "Waiting for services to be ready..."
#     until curl -s http://localhost/api1/health; do
#       echo "Waiting for backend to be ready..."
#       sleep 8
#     done
#     echo "Services are ready!"
#   continue-on-error: true

# # Debug
# - name: Debug
#   run: |
#     echo "Waiting for services to be ready..."
#     until curl -s http://localhost/api1/customers; do
#       echo "Waiting for backend to be ready..."
#       sleep 8
#     done
#     echo "Services are ready!"
#   continue-on-error: true

# - name: Run E2E tests ########### muista korjata db ongelma
#   run: npm run test:e2e
#   continue-on-error: true

# - name: Upload E2E Test Results
#   uses: actions/upload-artifact@v4
#   if: always()
#   with:
#     name: playwright-report
#     path: ./playwright-e2e/playwright-report/
#     retention-days: 30

# - name: Upload Screenshots as Artifacts
#   uses: actions/upload-artifact@v4
#   if: always()
#   with:
#     name: e2e-screenshots
#     path: ./screenshots/*.png

# - name: Stop and Remove Containers
#   run: |
#     docker-compose -f docker-compose.ci.yml down

# if ok, --> deploy to PROD

# destroy staging? vai stop?
